name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Save node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Restore node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules
      - name: Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Restore node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Build project
        run: npm run build

      - name: Save dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Restore node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Restore dist folder
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Run main file
        run: node dist/app.js
